exec(open('/tmp/up.py').read().split("# ---------- setup ----------")[0])
admin=web_login("head.dept@hospital.in")
P={"Age":"45","Sex":"Male","Mobile No.":"9876543210","Aadhaar Card No.":"123412341234","Bank Account No.":"000123456789","Amount Released":"No","Diagnosis":"Claw hand"}
call("POST","/api/special",{"kind":"LEPROSY","recordDate":"2026-09-05","primaryName":"Ram","payload":P},cookie=admin)
rid=int(sql("select max(id) from special_records where kind='LEPROSY'"))
P2={**P,"Aadhaar Card No.":"999988887777","Diagnosis":"Claw hand post-op"}
call("POST","/api/special",{"id":rid,"kind":"LEPROSY","recordDate":"2026-09-05","primaryName":"Ram","payload":P2,"status":"ACTIVE"},cookie=admin)
row=sql(f"select details from audit_logs where action='UPDATE' and module='LEPROSY' and record_id={rid} order by id desc limit 1")
ok("Aadhaar Card No." in row and "Diagnosis" in row and "999988887777" not in row and "123412341234" not in row, f"A1 Leprosy edit logs field names only: '{row}'")
# restore keeps the audit trail
c,d,_=call("POST","/api/admin/system",{"action":"backup"},cookie=admin); s,b,_=raw("GET",d["data"]["url"]); snap=json.loads(b)
before=int(sql("select count(*) from audit_logs"))
call("POST","/api/patients",{"name":"After Backup Patient","age":30,"sex":"Female","mobile":"9000000009","address":"x","diagnosis":"y"},cookie=admin)
marker=sql("select id from audit_logs where details like '%Registered%' order by id desc limit 1")
pkg=json.dumps(snap).encode()
c,d,_=call("POST","/api/admin/system",{"action":"restorePackageUrl","size":len(pkg)},cookie=admin); raw("PUT",d["data"]["uploadUrl"],pkg,{"content-type":"application/json"})
c,d,sc=call("POST","/api/admin/system",{"action":"restore","uploadId":d["data"]["uploadId"]},cookie=admin)
kept=sql(f"select count(*) from audit_logs where id={marker}")
gone=sql("select count(*) from patients where name='After Backup Patient'")
dupes=sql("select count(*) from (select created_at,action,details,count(*) from audit_logs group by 1,2,3 having count(*)>1) t")
last=sql("select action from audit_logs order by id desc limit 1")
ok(c==200 and gone=="0" and kept=="1", f"A2 restore rolled data back (patient gone) but kept the audit entry of the post-backup registration")
ok(dupes=="0", f"A3 no duplicated audit entries after restoring onto the same database (duplicates: {dupes})")
ok(last=="RESTORE", "A4 the restore itself is the latest audit entry")
