import os
# Client change round 3: OPD No./UHID No., DD-MM-YYYY, headings, sidebar boxes, dashboard, gap, Skin Bank tabs/status
exec(open('/tmp/up.py').read().split("# ---------- setup ----------")[0])
from playwright.sync_api import sync_playwright
import csv, io
admin=web_login("head.dept@hospital.in")
P={"name":"Meena Sahu","age":34,"sex":"Female","mobile":"9812000001","address":"Katni, Madhya Pradesh","diagnosis":"Post-burn contracture of the neck with restricted extension"}
c,d,_=call("POST","/api/patients",{**P,"opdNumber":"   "},cookie=admin); ok(c==400 and "OPD No." in d["message"], f"O1 OPD No./UHID No. is required -> {c}: {d['message']}")
c,d,_=call("POST","/api/patients",{**P,"opdNumber":"OPD/2026/1001"},cookie=admin); ok(c==201, f"O2 patient saved with OPD No. -> {c}")
c,d,_=call("POST","/api/patients",{**P,"name":"Other Person","mobile":"9812000002","opdNumber":"opd/2026/1001"},cookie=admin)
ok(c==409 and "already used by Meena Sahu" in d["message"], f"O3 duplicate (any letter case) -> {c}: {d['message']}")
call("POST","/api/patients",{**P,"name":"Ravi Kumar","mobile":"9812000003","opdNumber":"UHID-77"},cookie=admin)
_,pl,_=call("GET","/api/patients",cookie=admin); ravi=[x for x in pl["data"] if x["name"]=="Ravi Kumar"][0]
c,d,_=call("PATCH",f"/api/patients/{ravi['id']}",{**P,"name":"Ravi Kumar","mobile":"9812000003","opdNumber":"OPD/2026/1001"},cookie=admin); ok(c==409, f"O4 edit to a used number refused -> {c}")
_,s1,_=call("GET","/api/patients?q=1001",cookie=admin); ok([x["name"] for x in s1["data"]]==["Meena Sahu"], "O5 search finds the patient by OPD No.")
meena=[x for x in pl["data"] if x["name"]=="Meena Sahu"][0]; call("POST",f"/api/opd/{meena['opdId']}/admit",{},cookie=admin)
_,cl,_=call("GET","/api/clinical",cookie=admin); ok(cl["data"]["ipd"][0].get("opdNumber")=="OPD/2026/1001", "O6 IPD list carries the OPD No.")
s,b,_=raw("GET",B+"/api/reports/opd?format=csv",headers={"cookie":admin}); rows=list(csv.reader(io.StringIO(b.decode("utf-8-sig"))))
ok("OPD No./UHID" in rows[0] and re.match(r"^\d{2}-\d{2}-\d{4}$", rows[1][0]), f"R1 OPD report: OPD No. column and DD-MM-YYYY dates ({rows[0][:3]}, {rows[1][0]})")
call("POST","/api/special",{"kind":"SKIN_RECIPIENT","recordDate":"2026-09-14","primaryName":"Skin Pt","payload":{"CR No.":"1","UHID":"2","Age":"30","Sex":"Male","Address":"x","Mobile No.":"9876500099","Indication for Transplant":"raw area","Size of Graft Transplanted":"100"}},cookie=admin)
s,b,_=raw("GET",B+"/api/special?kind=SKIN_RECIPIENT&from=2026-09-01&to=2026-09-30&format=csv",headers={"cookie":admin}); r=list(csv.reader(io.StringIO(b.decode("utf-8-sig"))))
ok("Status" not in r[0] and r[1][1]=="14-09-2026", f"R2 Skin Bank export: no Status, date {r[1][1]}")
s,b,_=raw("GET",B+"/api/special?kind=LEPROSY&from=2026-09-01&to=2026-09-30&format=csv",headers={"cookie":admin}); ok("Status" in b.decode("utf-8-sig").splitlines()[0], "R3 Leprosy export keeps Status")
def nav(pg,x): pg.locator("[data-sidebar=menu-button]").filter(has_text=re.compile(rf"^\s*{x}\s*$",re.I)).first.click(); time.sleep(1.3)
with sync_playwright() as p:
    b=p.chromium.launch(executable_path=os.environ.get("CHROMIUM_PATH") or None); pg=b.new_page(viewport={"width":1440,"height":900})
    fresh(); pg.goto("http://localhost:3100/login"); pg.wait_for_selector("text=Send code"); pg.fill("input[type=email]","head.dept@hospital.in"); pg.click("text=Send code")
    pg.wait_for_selector("text=Enter your code"); time.sleep(0.3); pg.keyboard.type(last_code()[0])
    pg.wait_for_function("location.pathname === '/' || document.body.innerText.includes('Set your PIN')",timeout=15000)
    if "Set your PIN" in pg.inner_text("body"):
        pg.locator("#pin-new").focus(); pg.keyboard.type("2580"); pg.locator("#pin-confirm").focus(); pg.keyboard.type("2580"); pg.click("button:has-text('Save PIN')")
    pg.wait_for_url("http://localhost:3100/",timeout=15000); time.sleep(1.5)
    boxes=pg.evaluate("[...document.querySelectorAll('.nav-box .nav-box-label')].map(e=>e.innerText.replace(/\\s+/g,' ').trim())")
    ok(boxes==["CLINICAL WORKSPACE 5","ACADEMIC WORKSPACE 7"], f"S1 sidebar: two boxed groups with counts {boxes}")
    ok(pg.evaluate("getComputedStyle(document.querySelector('.brand-block span')).fontWeight")=="800", "S2 logo subtitle bold")
    fs=pg.evaluate("[getComputedStyle(document.querySelector('.dash-overview')).fontSize, getComputedStyle(document.querySelector('h1.greeting')).fontSize]")
    ok(fs[0]==fs[1]=="25px", f"D1 DEPARTMENT OVERVIEW as large as the greeting ({fs})")
    ok(pg.locator("text=Patient ID continuity").count()==0 and pg.locator("text=Production readiness").count()==0, "D2 side cards removed")
    w=pg.evaluate("[document.querySelector('.activity-panel').getBoundingClientRect().width, document.querySelector('.content-grid').getBoundingClientRect().width]")
    ok(abs(w[0]-w[1])<2, f"D3 activity takes the full width ({w})")
    ok(re.search(r"\d{2}-\d{2}-\d{4}", pg.inner_text(".activity-panel")) is not None, "D4 dashboard dates DD-MM-YYYY")
    pg.screenshot(path="/tmp/shots/s6-dash.png")
    gaps={}
    for mod,title in [("OPD","OPD PATIENTS"),("IPD","IPD"),("Ward","WARD"),("OT","OT"),("Class","CLASS"),("Research","RESEARCH"),("Publication","PUBLICATION"),("Skin Bank","SKIN BANK"),("Leprosy","LEPROSY"),("CM Helpline","CM HELPLINE"),("Admin","ADMINISTRATION")]:
        nav(pg,mod)
        h=pg.evaluate("(()=>{const h=document.querySelector('h1.section-title'); if(!h) return null; const cs=getComputedStyle(h); const top=document.querySelector('.topbar').getBoundingClientRect().bottom; return {t:h.innerText, w:cs.fontWeight, tt:cs.textTransform, gap:Math.round(document.querySelector('.workspace').firstElementChild.getBoundingClientRect().top-top), label:[...document.querySelectorAll('.eyebrow')].map(e=>e.innerText)}})()")
        gaps[mod]=h and h["gap"]
        ok(h and h["t"]==title and int(h["w"])>=700 and not h["label"], f"H {mod}: heading '{h and h['t']}' bold, no label above")
    ok(all(g is not None and g<=32 for g in gaps.values()), f"G empty space under the top bar is small on every page (px): {gaps}")
    nav(pg,"OPD"); heads=pg.evaluate("[...document.querySelectorAll('table.opd-table thead th')].map(t=>t.innerText.trim())")
    ok("OPD NO./UHID NO." in [x.upper() for x in heads] and "ADDRESS" in [x.upper() for x in heads], f"T1 OPD table columns {heads}")
    ok(re.search(r"\d{2}-\d{2}-\d{4}", pg.inner_text("table.opd-table tbody")) is not None and "OPD/2026/1001" in pg.inner_text("table.opd-table tbody"), "T2 OPD rows show OPD No. and DD-MM-YYYY")
    cw=pg.evaluate("(()=>{const th=[...document.querySelectorAll('table.opd-table thead th')]; const g=n=>th.find(t=>t.innerText.trim().toUpperCase()===n).getBoundingClientRect().width; return {patient:g('PATIENT'), diagnosis:g('DIAGNOSIS')}})()")
    ok(cw["diagnosis"]>cw["patient"], f"T3 Diagnosis column wider than Patient ({cw})")
    pg.screenshot(path="/tmp/shots/s6-opd.png")
    pg.click("button:has-text('Register OPD Patient')"); time.sleep(0.6)
    ok(pg.locator("[role=dialog] input[name=opdNumber]").count()==1, "F1 register form has OPD No./UHID No.")
    dlg="[role=dialog] "
    pg.fill(dlg+"input[name=name]","Kiran Das"); pg.fill(dlg+"input[name=age]","40"); pg.select_option(dlg+"select[name=sex]","Male"); pg.fill(dlg+"input[name=mobile]","9812000009")
    pg.fill(dlg+"input[name=opdNumber]","OPD/2026/1001"); pg.fill(dlg+"[name=diagnosis]","Scald"); pg.fill(dlg+"[name=address]","Jabalpur")
    pg.locator(dlg+"button[type=submit], "+dlg+"button:has-text('Save'), "+dlg+"button:has-text('Register')").last.click(); time.sleep(1.5)
    ok("already used by" in pg.inner_text("body"), "F2 duplicate OPD No. in the form shows a clear error")
    pg.fill(dlg+"input[name=opdNumber]","OPD/2026/1002"); pg.locator(dlg+"button[type=submit], "+dlg+"button:has-text('Save'), "+dlg+"button:has-text('Register')").last.click(); time.sleep(1.5)
    ok(sql("select opd_number from patients where name='Kiran Das'")=="OPD/2026/1002", "F3 corrected number saved from the form")
    nav(pg,"IPD"); ok("OPD/2026/1001" in pg.inner_text("table") and re.search(r"\d{2}-\d{2}-\d{4}", pg.inner_text("table")), "I1 IPD table shows OPD No. and DD-MM-YYYY")
    nav(pg,"Skin Bank"); tabs=pg.evaluate("[...document.querySelectorAll('.skin-tab')].map(t=>[t.innerText, getComputedStyle(t).backgroundColor])")
    ok([t[0] for t in tabs]==["RECIPIENTS","DONORS"] and tabs[0][1]!=tabs[1][1] and all(t[1] not in ("rgba(0, 0, 0, 0)","transparent") for t in tabs), f"K1 Skin Bank tabs in capitals with colours {tabs}")
    ok("STATUS" not in pg.inner_text("table thead").upper() and "14-09-2026" in pg.inner_text("table tbody"), "K2 Skin Bank table: no Status, DD-MM-YYYY")
    pg.click("button[aria-label='Edit Skin Pt']"); time.sleep(0.5); ok(pg.locator("[role=dialog] select[name=status]").count()==0, "K3 Skin Bank edit form has no Status"); pg.keyboard.press("Escape")
    pg.screenshot(path="/tmp/shots/s6-skin.png")
    nav(pg,"Leprosy"); ok("STATUS" in pg.inner_text("table thead").upper(), "K4 Leprosy keeps Status")
    b.close()
print(f"TOTAL: {R['pass']} passed, {R['fail']} failed")
