import os
# Client change round 2: app lock (PIN on every open, mandatory PIN), theme, capital sidebar, header weights, no formula box, tablet overflow
exec(open('/tmp/up.py').read().split("# ---------- setup ----------")[0])
from playwright.sync_api import sync_playwright
def ck(sc,n): return next((x.split(";")[0] for x in sc if x.startswith(n+"=")),None)
fresh(); call("POST","/api/auth/request-otp",{"email":"head.dept@hospital.in"}); code,_=last_code()
c,d,sc=call("POST","/api/auth/verify-otp",{"email":"head.dept@hospital.in","code":code}); sess=ck(sc,"dops_session")
ok(d["requirePin"] is True and ck(sc,"dops_unlock") is None, "L1 new browser: email code alone does not open the app; a PIN is required")
c,_,_=call("GET","/api/access",cookie=sess); ok(c==423, f"L2 locked session: data refused with 423 (not signed out) -> {c}")
c,_,_=call("POST","/api/auth/pin",{"action":"setup","pin":"2580","confirm":"2580"},cookie=sess); ok(c==401, "L3 a locked browser cannot set a PIN without the fresh email-code ticket")
c,_,sc2=call("POST","/api/auth/pin",{"action":"setup","pin":"2580","confirm":"2580"},cookie=f'{sess}; {ck(sc,"dops_pin_setup")}'); unlock=ck(sc2,"dops_unlock"); dev=ck(sc2,"dops_device")
full=f"{sess}; {unlock}"; c,_,_=call("GET","/api/access",cookie=full); ok(c==200, "L4 PIN set -> app unlocked")
unl=[x for x in sc2 if x.startswith("dops_unlock=")][0]; ok("Max-Age" not in unl and "Expires" not in unl, "L5 unlock cookie is a browser-session cookie (gone when the browser closes)")
c,_,_=call("POST","/api/auth/pin",{"action":"lock"},cookie=full); c2,_,_=call("GET","/api/access",cookie=sess); ok(c==200 and c2==423, "L6 lock (new tab/launch) -> locked again")
n=int(sql("select count(*) from auth_sessions where revoked_at is null"))
c,_,sc3=call("POST","/api/auth/pin",{"action":"login","pin":"2580"},cookie=f"{sess}; {dev}")
ok(c==200 and ck(sc3,"dops_unlock") and int(sql("select count(*) from auth_sessions where revoked_at is null"))==n, "L7 PIN unlocks the same session (no new session created)")
c,_,_=call("GET","/api/access",cookie=f'{sess}; {ck(sc3,"dops_unlock")}'); ok(c==200, "L8 unlocked again")
c,d,_=call("GET","/api/access",cookie=f"{sess}; dops_unlock=forged"); ok(c==423, "L9 forged unlock cookie refused")
fresh(); call("POST","/api/auth/request-otp",{"email":"head.dept@hospital.in"}); code,_=last_code()
c,d,_=call("POST","/api/auth/verify-otp",{"email":"head.dept@hospital.in","code":code,"client":"MOBILE"}); c2,_,_=call("GET","/api/access",bearer=d["token"])
ok(c2==200, "L10 mobile-app tokens are not affected by the web app lock")
admin=full
call("POST","/api/special",{"kind":"SKIN_RECIPIENT","recordDate":time.strftime("%Y-%m-%d"),"primaryName":"Wide Table Patient","payload":{"CR No.":"1234567","UHID":"99887766","Age":"40","Sex":"Male","Address":"Jabalpur, Madhya Pradesh","Mobile No.":"9876500011","Indication for Transplant":"Post-burn raw area over both lower limbs","Size of Graft Transplanted":"400 sq cm"}},cookie=admin)
with sync_playwright() as p:
    b=p.chromium.launch(executable_path=os.environ.get("CHROMIUM_PATH") or None)
    ctx=b.new_context(viewport={"width":1280,"height":800}); pg=ctx.new_page()
    ctx.add_cookies([{"name":"dops_device","value":dev.split("=",1)[1],"url":"http://localhost:3100","expires":time.time()+365*86400,"httpOnly":True}])
    fresh(); pg.goto("http://localhost:3100/"); pg.wait_for_url("**/login**")
    pg.wait_for_selector("text=Welcome back",timeout=10000); ok(True,"U1 opening DOPS with a PIN device shows the PIN screen")
    pg.keyboard.type("2580"); pg.wait_for_url("http://localhost:3100/",timeout=10000); time.sleep(1)
    pg.reload(); time.sleep(1.5); ok(pg.url=="http://localhost:3100/", "U2 reload in the same tab keeps it open (no PIN)")
    t2=ctx.new_page(); t2.goto("http://localhost:3100/"); t2.wait_for_url("**/login**",timeout=10000); t2.wait_for_selector("text=Welcome back",timeout=10000)
    ok(True,"U3 opening DOPS again in a new tab asks for the PIN")
    pg.locator("[data-sidebar=menu-button]").filter(has_text=re.compile(r"^\s*OPD\s*$",re.I)).first.click()
    pg.wait_for_url("**/login**",timeout=10000); ok("locked" in pg.url, "U4 the other tab is locked too as soon as it loads data")
    t2.keyboard.type("2580"); t2.wait_for_url("http://localhost:3100/",timeout=10000); time.sleep(1)
    state=ctx.storage_state(); persistent=[c for c in state["cookies"] if c.get("expires",-1)!=-1]
    ctx2=b.new_context(viewport={"width":1280,"height":800}); ctx2.add_cookies(persistent); r=ctx2.new_page()
    r.goto("http://localhost:3100/"); r.wait_for_url("**/login**",timeout=10000); r.wait_for_selector("text=Welcome back",timeout=10000)
    ok(True,"U5 browser closed and reopened (session cookies gone): PIN screen, still signed in")
    r.keyboard.type("2580"); r.wait_for_url("http://localhost:3100/",timeout=10000); time.sleep(1.5)
    st=r.evaluate("""(()=>{const g=(s)=>document.querySelector(s); const cs=(e)=>e?getComputedStyle(e):null;
      const side=cs(g('[data-sidebar=sidebar]')); const act=cs(g('[data-sidebar=menu-button][data-active=true]')); const menu=cs(g('[data-sidebar=menu-button]'));
      const dept=cs(g('.topbar-title strong')); const col=cs(g('.topbar-title strong + span')); const card=cs(g('.stats-grid .stat-card'));
      return {side:side&&side.backgroundColor, act:act&&act.backgroundImage.slice(0,40), tt:menu&&menu.textTransform, dw:dept&&dept.fontWeight, cw:col&&col.fontWeight,
        dept:g('.topbar-title strong')?.innerText, col:g('.topbar-title strong + span')?.innerText, sub:g('.brand-block span')?.innerText, card:card&&card.backgroundColor}})()""")
    ok(st["side"]=="rgb(18, 18, 18)" and "linear-gradient" in st["act"] and st["card"]=="rgb(252, 235, 199)", f"T1 black sidebar, gold active item, pastel stat card ({st['side']}, {st['card']})")
    ok(st["tt"]=="uppercase" and st["sub"]=="PLASTIC AND RECONSTRUCTIVE SURGERY", f"T2 sidebar menu and subtitle in CAPITALS ({st['sub']})")
    print("   header text:", repr(st["dept"]), repr(st["col"]))
    ok(st["dept"].strip().upper()=="PLASTIC AND RECONSTRUCTIVE SURGERY" and int(st["dw"])>=700 and st["col"].strip().upper()=="NSCB MEDICAL COLLEGE, JABALPUR" and int(st["cw"])<=500, f"T3 header: department bold ({st['dw']}), college normal ({st['cw']})")
    r.screenshot(path="/tmp/shots/s5-dash.png")
    for mod in ["Skin Bank","Leprosy"]:
        r.locator("[data-sidebar=menu-button]").filter(has_text=re.compile(rf"^\s*{mod}\s*$",re.I)).first.click(); time.sleep(1.5)
        w=r.evaluate("({doc:document.documentElement.scrollWidth, win:window.innerWidth, body:document.body.scrollWidth})")
        ok(w["doc"]<=w["win"] and w["body"]<=w["win"], f"W {mod} at 1280px: page not wider than the screen ({w})")
        ok(r.locator("text=Basic formula").count()==0, f"F {mod}: no 'Basic formula' box")
    r.add_style_tag(content="[data-slot=sidebar-inset], .workspace, .workspace > *, .panel { min-width: auto !important; }"); time.sleep(0.5)
    wb=r.evaluate("({doc:document.documentElement.scrollWidth, win:window.innerWidth})")
    print(f"   without the fix the page would be {wb['doc']}px on a {wb['win']}px screen")
    r.reload(); time.sleep(1.5)
    r.screenshot(path="/tmp/shots/s5-leprosy.png")
    tab=b.new_context(viewport={"width":800,"height":1280},is_mobile=True,has_touch=True,device_scale_factor=2); tab.add_cookies(persistent); tp=tab.new_page()
    tp.goto("http://localhost:3100/"); tp.wait_for_selector("text=Welcome back",timeout=10000); tp.keyboard.type("2580"); tp.wait_for_url("http://localhost:3100/",timeout=10000); time.sleep(1)
    tp.evaluate("document.querySelector('[data-sidebar=trigger]')?.click()"); time.sleep(0.6)
    m=tp.locator("[data-sidebar=menu-button]").filter(has_text=re.compile(r"^\s*Skin Bank\s*$",re.I)).first
    m.evaluate("e => e.click()")
    time.sleep(1.5); vv=tp.evaluate("({doc:document.documentElement.scrollWidth, win:window.innerWidth, scale:window.visualViewport?window.visualViewport.scale:1})")
    ok(vv["doc"]<=vv["win"], f"W tablet (mobile browser, 800px) Skin Bank: page fits the screen, no zoom-out ({vv})")
    tp.screenshot(path="/tmp/shots/s5-tablet.png")
    b.close()
print(f"TOTAL: {R['pass']} passed, {R['fail']} failed")
