import os
# Polishing round: emergency OPD, IPD/Ward flow (MLC, STATUS, rows kept), dashboard cards, Age/Sex, month labels, Skin Bank inline editing
exec(open('/tmp/up.py').read().split("# ---------- setup ----------")[0])
from playwright.sync_api import sync_playwright
import csv, io, datetime
IST_TODAY=(datetime.datetime.utcnow()+datetime.timedelta(hours=5,minutes=30)).strftime("%Y-%m-%d")
admin=web_login("head.dept@hospital.in")
def add(name,mobile,opd,vt="OPD"):
    c,d,_=call("POST","/api/patients",{"name":name,"age":40,"sex":"Male","mobile":mobile,"address":"Jabalpur","diagnosis":"Burn injury","opdNumber":opd,"visitType":vt},cookie=admin); return c
ok(add("Emergency Ram","9811100001","EM-1","EMERGENCY")==201 and add("Regular Shyam","9811100002","OPD-1")==201, "E1 OPD and Emergency OPD registrations")
_,em,_=call("GET","/api/patients?type=EMERGENCY",cookie=admin); _,op,_=call("GET","/api/patients",cookie=admin)
ok([x["name"] for x in em["data"]]==["Emergency Ram"] and [x["name"] for x in op["data"]]==["Regular Shyam"], "E2 each list shows only its own visits")
s,b,_=raw("GET",B+"/api/reports/emergency?format=csv",headers={"cookie":admin}); s2,b2,_=raw("GET",B+"/api/reports/opd?format=csv",headers={"cookie":admin})
ok(s==200 and "Emergency Ram" in b.decode() and "Emergency Ram" not in b2.decode() and "Regular Shyam" in b2.decode(), "E3 separate Emergency OPD and OPD registers")
for p in em["data"]+op["data"]: call("POST",f"/api/opd/{p['opdId']}/admit",{},cookie=admin)
_,cl,_=call("GET","/api/clinical",cookie=admin); ipd={x["name"]:x["id"] for x in cl["data"]["ipd"]}
c,_,_=call("POST","/api/clinical",{"action":"case_category","id":ipd["Emergency Ram"],"category":"MLC"},cookie=admin)
c2,_,_=call("POST","/api/clinical",{"action":"case_category","id":ipd["Emergency Ram"],"category":"MAYBE"},cookie=admin)
ok(c==200 and c2==400, "C1 case category MLC saved; other values refused")
for n in ipd: call("POST","/api/clinical",{"action":"move_ward","id":ipd[n],"wardName":"Burns A","bedNumber":"1"},cookie=admin)
_,cl,_=call("GET","/api/clinical",cookie=admin); wd={x["name"]:x["wardId"] for x in cl["data"]["ward"]}
ok([x["caseCategory"] for x in cl["data"]["ward"] if x["name"]=="Emergency Ram"]==["MLC"], "C2 case category shows in Ward")
c,d,_=call("POST","/api/clinical",{"action":"discharge","wardId":wd["Emergency Ram"],"notes":"ok","status":"XYZ"},cookie=admin); ok(c==400, f"W1 invalid exit status refused -> {c}")
c,_,_=call("POST","/api/clinical",{"action":"discharge","wardId":wd["Emergency Ram"],"notes":"left","status":"LAMA"},cookie=admin)
_,cl,_=call("GET","/api/clinical",cookie=admin); row=[x for x in cl["data"]["ward"] if x["name"]=="Emergency Ram"][0]
ok(c==200 and row["dischargedAt"] and row["dischargeStatus"]=="LAMA", "W2 discharged as LAMA; the ward row still exists")
ok(any(x["name"]=="Emergency Ram" for x in cl["data"]["ipd"]), "W3 patient still listed in IPD")
c,_,_=call("POST","/api/clinical",{"action":"ward_status","wardId":wd["Emergency Ram"],"status":"DAMA"},cookie=admin); c2,_,_=call("POST","/api/clinical",{"action":"ward_status","wardId":wd["Regular Shyam"],"status":"DOR"},cookie=admin)
ok(c==200 and c2==404, "W4 status can be changed after discharge; not for a patient still in the ward")
call("POST","/api/special",{"kind":"SKIN_RECIPIENT","recordDate":IST_TODAY,"primaryName":"Inline Pt","payload":{"CR No.":"1","UHID":"2","Age":"30","Sex":"Male","Address":"x","Mobile No.":"9876500099","Indication for Transplant":"raw area","Size of Graft Transplanted":"100"}},cookie=admin)
call("POST","/api/special",{"kind":"LEPROSY","recordDate":IST_TODAY,"primaryName":"Lep Pt","payload":{"Age":"55","Sex":"Female","Mobile No.":"9876500098","Amount Released":"No"}},cookie=admin)
def nav(pg,x): pg.locator("[data-sidebar=menu-button]").filter(has_text=re.compile(rf"^\s*{x}\s*$",re.I)).first.click(); time.sleep(1.3)
with sync_playwright() as p:
    b=p.chromium.launch(executable_path=os.environ.get("CHROMIUM_PATH") or None); pg=b.new_page(viewport={"width":1440,"height":900})
    fresh(); pg.goto("http://localhost:3100/login"); pg.wait_for_selector("text=Send code"); pg.fill("input[type=email]","head.dept@hospital.in"); pg.click("text=Send code")
    pg.wait_for_selector("text=Enter your code"); time.sleep(0.3); pg.keyboard.type(last_code()[0])
    pg.wait_for_function("location.pathname === '/' || document.body.innerText.includes('Set your PIN')",timeout=15000)
    if "Set your PIN" in pg.inner_text("body"):
        pg.locator("#pin-new").focus(); pg.keyboard.type("2580"); pg.locator("#pin-confirm").focus(); pg.keyboard.type("2580"); pg.click("button:has-text('Save PIN')")
    pg.wait_for_url("http://localhost:3100/",timeout=15000); time.sleep(1.8)
    cards=pg.evaluate("[...document.querySelectorAll('.stats-grid .stat-card')].map(c=>c.querySelector('span').innerText+'='+c.querySelector('strong').innerText)")
    ok(len(cards)==5 and cards[1]=="Today's IPD=2" and cards[4]=="Today Discharged=1", f"D1 dashboard cards {cards}")
    labels=pg.evaluate("[...document.querySelectorAll('.nav-box .nav-box-label')].map(e=>e.innerText.replace(/\\s+/g,' ').trim())")
    ok(labels[0]=="CLINICAL WORKSPACE 6" and pg.locator("[data-sidebar=menu-button]", has_text=re.compile("Emergency OPD",re.I)).count()==1, f"N1 Emergency OPD under Clinical Workspace {labels}")
    pg.screenshot(path="/tmp/shots/s7-dash.png")
    nav(pg,"Emergency OPD"); ok(pg.inner_text("h1.section-title")=="EMERGENCY OPD" and "Emergency Ram" in pg.inner_text("table") and "Regular Shyam" not in pg.inner_text("table"), "N2 Emergency OPD page lists only emergency visits")
    pg.click("button:has-text('Register Emergency Patient')"); time.sleep(0.5); dlg="[role=dialog] "
    ok("Register Emergency OPD patient" in pg.inner_text("[role=dialog]"), "N3 register dialog titled for Emergency OPD")
    pg.fill(dlg+"input[name=name]","Night Case"); pg.fill(dlg+"input[name=age]","22"); pg.select_option(dlg+"select[name=sex]","Female"); pg.fill(dlg+"input[name=mobile]","9811100009")
    pg.fill(dlg+"input[name=opdNumber]","EM-9"); pg.fill(dlg+"[name=diagnosis]","Scald"); pg.fill(dlg+"[name=address]","Jabalpur"); pg.click(dlg+"button[type=submit]"); time.sleep(1.5)
    ok(sql("select o.visit_type from opd_visits o join patients p on p.id=o.patient_id where p.name='Night Case'")=="EMERGENCY", "N4 registered from Emergency OPD -> saved as an emergency visit")
    heads=pg.evaluate("[...document.querySelectorAll('table thead th')].map(t=>t.innerText.trim().toUpperCase())"); ok("PATIENT NAME" in heads, "P1 'Patient Name' column header")
    nav(pg,"IPD"); badges=pg.evaluate("[...document.querySelectorAll('table tbody .clinical-badge')].map(b=>b.innerText.trim().toUpperCase())")
    ok(badges and all(x=="ADMITTED" for x in badges), f"I1 IPD status is always ADMITTED {badges}")
    sel=pg.locator("select[aria-label='Case category for Regular Shyam']"); sel.select_option("NON-MLC"); time.sleep(1.2)
    ok(sql(f"select case_category from ipd_admissions where id={ipd['Regular Shyam']}")=="NON-MLC", "I2 CASE CATEGORY dropdown saves")
    pg.screenshot(path="/tmp/shots/s7-ipd.png")
    nav(pg,"Ward"); t=pg.inner_text("table")
    ok("Emergency Ram" in t and "Regular Shyam" in t, "WU1 discharged patient still shown in Ward")
    st=pg.locator("select[aria-label='Status for Emergency Ram']"); ok(st.input_value()=="DAMA", "WU2 STATUS dropdown shows how the patient left")
    st.select_option("DOR"); time.sleep(1.2); ok(sql(f"select discharge_status from ward_stays where id={wd['Emergency Ram']}")=="DOR", "WU3 STATUS changed from the table")
    ok("MLC" in t and "NON-MLC" in t, "WU4 case category visible in Ward")
    pg.locator("tr", has_text="Regular Shyam").locator("button:has-text('Discharge')").click(); time.sleep(0.5)
    opts=pg.eval_on_selector("[role=dialog] select[name=status]","s=>[...s.options].map(o=>o.text)"); ok(opts==["DISCHARGED","LAMA","DOR","DAMA"], f"WU5 discharge dialog STATUS {opts}")
    pg.keyboard.press("Escape"); pg.screenshot(path="/tmp/shots/s7-ward.png")
    nav(pg,"Skin Bank"); heads=pg.evaluate("[...document.querySelectorAll('table thead th')].map(t=>t.innerText.trim().toUpperCase())")
    ok("AGE/SEX" in heads and "SEX" not in heads and "30 / M" in pg.inner_text("table tbody"), "A1 Skin Bank Age/Sex column")
    ml=pg.eval_on_selector("select.register-month","s=>[...s.options].map(o=>o.text)"); ok("OCT 2026" in ml and "SEPT 2026" in ml, f"M1 month labels ({ml[:3]})")
    pg.click("td[aria-label='Edit name of Inline Pt']"); pg.keyboard.press("Control+A"); pg.keyboard.type("Inline Patient"); pg.keyboard.press("Enter"); time.sleep(1.5)
    ok(sql("select primary_name from special_records where kind='SKIN_RECIPIENT'")=="Inline Patient", "X1 tap a cell, type, Enter -> saved (Excel-style)")
    pg.click("td[aria-label='Edit Age/Sex of Inline Patient']"); time.sleep(0.3); pg.fill("td.cell-editing input[aria-label=Age]","31"); pg.select_option("td.cell-editing select[aria-label=Sex]","Female"); pg.keyboard.press("Enter"); time.sleep(1.5)
    ok('"Age":"31"' in sql("select payload from special_records where kind='SKIN_RECIPIENT'") and "31 / F" in pg.inner_text("table tbody"), "X2 Age/Sex edited inline")
    pg.click("td[aria-label='Edit Address of Inline Patient']"); pg.keyboard.type("zzz"); pg.keyboard.press("Escape"); time.sleep(0.5)
    ok("zzz" not in sql("select payload from special_records where kind='SKIN_RECIPIENT'"), "X3 Escape cancels without saving")
    pg.screenshot(path="/tmp/shots/s7-skin.png")
    nav(pg,"Leprosy"); ok("AGE/SEX" in [x.upper() for x in pg.evaluate("[...document.querySelectorAll('table thead th')].map(t=>t.innerText.trim())")] and "55 / F" in pg.inner_text("table tbody"), "A2 Leprosy Age/Sex column")
    b.close()
print(f"TOTAL: {R['pass']} passed, {R['fail']} failed")
