export const uatChecks = [
  { id: "CLINICAL_01", area: "Clinical workflow", tester: "Resident / Staff", title: "Register a new OPD patient", steps: ["Register a dummy patient with complete demographics and diagnosis.", "Search using name, Patient ID and diagnosis."], expected: "A unique Patient ID is generated and the patient appears in OPD search." },
  { id: "CLINICAL_02", area: "Clinical workflow", tester: "Doctor / Resident", title: "Admit OPD patient to IPD", steps: ["Open the dummy OPD entry and select Admit.", "Open IPD and compare demographics and diagnosis."], expected: "Demographics and diagnosis carry forward without duplicate entry." },
  { id: "CLINICAL_03", area: "Clinical workflow", tester: "Nurse / Resident", title: "Move IPD patient to Ward", steps: ["Assign a ward and unused bed to the admitted patient.", "Set PAC to Fit and verify the active ward list."], expected: "Ward, bed and PAC status appear in the active ward census." },
  { id: "CLINICAL_04", area: "Clinical workflow", tester: "Doctor / Resident", title: "Schedule and complete OT", steps: ["Schedule OT for today or tomorrow with procedure and surgeon.", "Find it in the correct tab and mark it Completed."], expected: "Patient appears in the correct OT date tab with PAC and procedure details." },
  { id: "CLINICAL_05", area: "Clinical workflow", tester: "Doctor / Resident", title: "Upload OT pre-op and post-op images", steps: ["Upload one JPG/PNG to each image category.", "Open both images, then verify a user without OT access cannot open them."], expected: "Authorized users can view images; unauthorized modules cannot access them." },
  { id: "CLINICAL_06", area: "Clinical workflow", tester: "Doctor / Nurse", title: "Discharge patient with card", steps: ["Upload a dummy discharge card and complete discharge.", "Confirm removal from active ward and open the patient timeline/card."], expected: "Patient leaves active ward, card remains available and timeline is retained." },
  { id: "ACCESS_01", area: "Access & security", tester: "Admin + every role", title: "Verify every department role", steps: ["Create or approve Doctor, Resident, Nurse and Staff test users.", "Sign in as each role and attempt allowed and disallowed actions."], expected: "Admin, Doctor, Resident, Nurse and Staff see only granted modules and actions." },
  { id: "ACCESS_02", area: "Access & security", tester: "Admin", title: "Verify deactivated user", steps: ["Deactivate a test user from Admin.", "Retry data access using that user's session."], expected: "A deactivated account cannot read or modify department data." },
  { id: "ACCESS_03", area: "Access & security", tester: "Admin + restricted user", title: "Verify medical file permissions", steps: ["Open a permitted PDF, card and OT image.", "Remove the relevant permission and retry every file URL."], expected: "PDFs, discharge cards and OT images require the matching module permission." },
  { id: "DATA_01", area: "Data quality", tester: "Staff / Resident", title: "Check duplicate patient protection", steps: ["Register a dummy patient.", "Repeat registration with the same name and mobile number."], expected: "A matching name and mobile number produces a duplicate warning." },
  { id: "REPORT_01", area: "Reports & registers", tester: "Admin / Doctor", title: "Export monthly OPD and OT reports", steps: ["Select a month containing the dummy records.", "Download PDF and CSV and compare dates, rows and totals."], expected: "PDF and CSV contain the selected period and correct patient totals." },
  { id: "REPORT_02", area: "Reports & registers", tester: "Admin / Authorized staff", title: "Verify Skin Bank and Leprosy registers", steps: ["Create one dummy recipient, donor and Leprosy row.", "Filter by month, check masking and download the exports."], expected: "Official columns, month filters, masking and Excel/CSV exports are correct." },
  { id: "SPECIAL_01", area: "Special modules", tester: "Doctor / Resident", title: "Link patient to CM Helpline", steps: ["Add the dummy patient to CM Helpline from OPD/IPD.", "Confirm carried details and update case status through Resolved."], expected: "Patient details are carried from OPD/IPD and case status can be tracked." },
  { id: "ACADEMIC_01", area: "Academic modules", tester: "Doctor / Resident", title: "Upload and retrieve academic documents", steps: ["Upload dummy PDFs in Class, Research and Publication; add a publication link.", "Search each record and open its protected file/link."], expected: "Class, Research and Publication PDFs and links are searchable and protected." },
  { id: "OFFLINE_01", area: "Mobile & offline", tester: "Staff / Resident", title: "Register OPD patient without internet", steps: ["Disconnect the device and save one dummy OPD registration.", "Reconnect, select Sync now and search for the generated patient."], expected: "Entry stays on the device and syncs once connectivity returns." },
  { id: "MOBILE_01", area: "Mobile & offline", tester: "Doctor / Nurse", title: "Complete rounds workflow on mobile", steps: ["Use a real phone to open Dashboard, Ward, OT and patient timeline.", "Complete one PAC update and verify all buttons/forms without zooming."], expected: "Navigation, forms, tables and actions remain usable without horizontal clipping." },
  { id: "RECOVERY_01", area: "Recovery", tester: "Admin", title: "Download complete recovery ZIP", steps: ["Download a recovery package after adding dummy files.", "Open the ZIP and verify database.json plus expected files."], expected: "Database, PDFs, discharge cards and OT images are present in the package." },
  { id: "RECOVERY_02", area: "Recovery", tester: "Admin + technical owner", title: "Restore verified recovery ZIP", steps: ["Use a controlled non-production copy and type the restore confirmation phrase.", "Verify record totals, file access and active Admin access after restore."], expected: "Records and files are restored and the current active Admin remains authorized." },
] as const;

export const uatIds = new Set<string>(uatChecks.map((check) => check.id));
